-- INSERT INTO composer (name, year_of_birth, year_of_death) VALUES ('Liszt Ferenc', 1810, 1886);
--
-- INSERT INTO publisher (name) VALUES ('Bärenreiter Publishers');
--
-- INSERT INTO score (instrument_type, is_available_in_stock, price, title, year_of_creation, composer_id, publisher_id) VALUES ('PIANO', true, 5000.00, 'Hungarian Rhapsody No.2', 1847, 1, 1);
