INSERT INTO composer (name, year_of_birth, year_of_death) VALUES ('Giovanni Pierluigi da Palestrina', 1525, 1594);
INSERT INTO composer (name, year_of_birth, year_of_death) VALUES ('Claudio Monteverdi', 1567, 1643);
INSERT INTO composer (name, year_of_birth, year_of_death) VALUES ('Antonio Vivaldi', 1678, 1741);
INSERT INTO composer (name, year_of_birth, year_of_death) VALUES ('Johann Sebastian Bach', 1685, 1750);
INSERT INTO composer (name, year_of_birth, year_of_death) VALUES ('Georg Friedrich Händel', 1685, 1859);
INSERT INTO composer (name, year_of_birth, year_of_death) VALUES ('Joseph Haydn', 1732, 1809);
INSERT INTO composer (name, year_of_birth, year_of_death) VALUES ('Wolfgang Amadeus Mozart', 1756, 1791);
INSERT INTO composer (name, year_of_birth, year_of_death) VALUES ('Ludwig van Beethoven', 1770, 1827);
INSERT INTO composer (name, year_of_birth, year_of_death) VALUES ('Franz Schubert', 1797, 1828);
INSERT INTO composer (name, year_of_birth, year_of_death) VALUES ('Frédéric Chopin', 1810, 1849);
INSERT INTO composer (name, year_of_birth, year_of_death) VALUES ('Ferenc Liszt', 1811, 1886);
INSERT INTO composer (name, year_of_birth, year_of_death) VALUES ('Johannes Brahms', 1833, 1897);
INSERT INTO composer (name, year_of_birth, year_of_death) VALUES ('Pjotr Iljics Csajkovszkij', 1840, 1893);
INSERT INTO composer (name, year_of_birth, year_of_death) VALUES ('Claude Debussy', 1862, 1918);
INSERT INTO composer (name, year_of_birth, year_of_death) VALUES ('Igor Sztravinszkij', 1882, 1971);
INSERT INTO composer (name, year_of_birth, year_of_death) VALUES ('Béla Bartók', 1882, 1945);

INSERT INTO publisher (name) VALUES ('Bärenreiter Publishers');
INSERT INTO publisher (name) VALUES ('Editio Musica Budapest');
INSERT INTO publisher (name) VALUES ('Boosey and Hawkes');
INSERT INTO publisher (name) VALUES ('G. Henle Publishers');
INSERT INTO publisher (name) VALUES ('MusicNotes');
INSERT INTO publisher (name) VALUES ('Edition Peters');
INSERT INTO publisher (name) VALUES ('Wiener Urtext Edition');

INSERT INTO score (instrument_type, is_available_in_stock, price, title, year_of_creation, composer_id, publisher_id) VALUES ('CLARINET', true, 4500, 'Clarinet Concerto in A major', 1791, 7, 7);
INSERT INTO score (instrument_type, is_available_in_stock, price, title, year_of_creation, composer_id, publisher_id) VALUES ('CLARINET', false, 6000, 'Clarinet Sonata No. 2 in E flat', 1894, 12, 6);
INSERT INTO score (instrument_type, is_available_in_stock, price, title, year_of_creation, composer_id, publisher_id) VALUES ('FLUTE', true, 3500, 'Syrinx', 1913, 14, 3);
INSERT INTO score (instrument_type, is_available_in_stock, price, title, year_of_creation, composer_id, publisher_id) VALUES ('FLUTE', false, 7000, 'Prélude à l''après-midi d’un faune', 1894, 14, 3);
INSERT INTO score (instrument_type, is_available_in_stock, price, title, year_of_creation, composer_id, publisher_id) VALUES ('PIANO', true, 5000, 'Hungarian Rhapsody No.2', 1847, 11, 2);
INSERT INTO score (instrument_type, is_available_in_stock, price, title, year_of_creation, composer_id, publisher_id) VALUES ('PIANO', true, 6500, 'Sonata in B minor', 1854, 11, 2);
INSERT INTO score (instrument_type, is_available_in_stock, price, title, year_of_creation, composer_id, publisher_id) VALUES ('PIANO', false, 6500, 'Ballade in G minor', 1835, 10, 5);
INSERT INTO score (instrument_type, is_available_in_stock, price, title, year_of_creation, composer_id, publisher_id) VALUES ('VIOLIN', true, 5500, 'Violin Concerto in A minor', 1711, 3, 4);
INSERT INTO score (instrument_type, is_available_in_stock, price, title, year_of_creation, composer_id, publisher_id) VALUES ('CELLO', false, 4500, 'Cello Suite in G minor', 1717, 4, 1);
INSERT INTO score (instrument_type, is_available_in_stock, price, title, year_of_creation, composer_id, publisher_id) VALUES ('ORGAN', true, 7000, 'Triosonatas', 1726, 4, 1);
INSERT INTO score (instrument_type, is_available_in_stock, price, title, year_of_creation, composer_id, publisher_id) VALUES ('VOICE', true, 4000, 'Winterreise', 1827, 9, 7);
INSERT INTO score (instrument_type, is_available_in_stock, price, title, year_of_creation, composer_id, publisher_id) VALUES ('TRUMPET', true, 3500, 'Trumpet Concerto in E-Flat Major', 1796, 6, 6);
INSERT INTO score (instrument_type, is_available_in_stock, price, title, year_of_creation, composer_id, publisher_id) VALUES ('GUITAR', true, 4400, 'Guitar concerto in D major', 1731, 3, 5);
INSERT INTO score (instrument_type, is_available_in_stock, price, title, year_of_creation, composer_id, publisher_id) VALUES ('OBOE', false, 5300, 'Sonata in C major for Oboe and Continuo', 1733, 4, 7);
INSERT INTO score (instrument_type, is_available_in_stock, price, title, year_of_creation, composer_id, publisher_id) VALUES ('HORN', true, 5900, 'Horn Concerto No. 4 in E flat', 1786, 7, 7);
