CREATE TABLE composer
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255),
    year_of_birth INTEGER                                 NOT NULL,
    year_of_death INTEGER                                 NOT NULL,
    CONSTRAINT pk_composer PRIMARY KEY (id)
);

CREATE TABLE composer_scores
(
    composer_id BIGINT NOT NULL,
    scores_id   BIGINT NOT NULL
);

CREATE TABLE publisher
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_publisher PRIMARY KEY (id)
);

CREATE TABLE publisher_scores
(
    publisher_id BIGINT NOT NULL,
    scores_id    BIGINT NOT NULL
);

CREATE TABLE score
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title                 VARCHAR(255),
    composer_id           BIGINT                                  NOT NULL,
    instrument_type       VARCHAR(255)                            NOT NULL,
    year_of_creation      INTEGER                                 NOT NULL,
    price                 DOUBLE PRECISION                        NOT NULL,
    publisher_id          BIGINT                                  NOT NULL,
    is_available_in_stock BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_score PRIMARY KEY (id)
);

ALTER TABLE composer_scores
    ADD CONSTRAINT uc_composer_scores_scores UNIQUE (scores_id);

ALTER TABLE publisher_scores
    ADD CONSTRAINT uc_publisher_scores_scores UNIQUE (scores_id);

ALTER TABLE score
    ADD CONSTRAINT FK_SCORE_ON_COMPOSER FOREIGN KEY (composer_id) REFERENCES composer (id);

ALTER TABLE score
    ADD CONSTRAINT FK_SCORE_ON_PUBLISHER FOREIGN KEY (publisher_id) REFERENCES publisher (id);

ALTER TABLE composer_scores
    ADD CONSTRAINT fk_comsco_on_composer FOREIGN KEY (composer_id) REFERENCES composer (id);

ALTER TABLE composer_scores
    ADD CONSTRAINT fk_comsco_on_score FOREIGN KEY (scores_id) REFERENCES score (id);

ALTER TABLE publisher_scores
    ADD CONSTRAINT fk_pubsco_on_publisher FOREIGN KEY (publisher_id) REFERENCES publisher (id);

ALTER TABLE publisher_scores
    ADD CONSTRAINT fk_pubsco_on_score FOREIGN KEY (scores_id) REFERENCES score (id);

DROP TABLE score_composers CASCADE;